qui 02 jul 2026 17:46:48 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/usr/local/bin/svlogtail b/usr/local/bin/svlogtail
--- a/usr/local/bin/svlogtail
+++ b/usr/local/bin/svlogtail
@@ -1,9 +1,9 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 LOGROOT="/var/log/socklog"
 
 usage () {
-	cat <<-EOF
+  cat <<-EOF
 	Usage: svlogtail [LOG...]
 
 	Examples:
@@ -12,8 +12,28 @@ usage () {
 	  svlogtail auth
 	  svlogtail daemon
 	  svlogtail messages
-	EOF
+EOF
 }
+
+sh_checkroot() {
+  (( EUID != 0 )) && elevate_to_root "$@" || return 0
+}
+
+elevate_to_root() {
+  echo -e "This script must be run as root. Elevating privileges..."
+  ccabec+='root [elevated]'
+  # Tenta usar sudo primeiro (caso esteja configurado)
+  if command -v sudo >/dev/null 2>&1; then
+    exec sudo bash "$0" "$@"
+  fi
+  # Se sudo falhar, tenta su
+  if command -v su >/dev/null 2>&1; then
+    exec su -c "$0 $*"
+  fi
+  echo -e "Error: Unable to elevate privileges. Run manually as root."
+  exit 1
+}
+
 
 # Resolve argumento como caminho OU nome
 resolve_log() {
@@ -80,6 +100,8 @@ colorize() {
 }
 
 # -------------- MAIN --------------
+
+sh_checkroot "$@"
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 	usage
