qui 11 jun 2026 17:34:12 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/pkgfile/PKGFILE b/pkgfile/PKGFILE
--- a/pkgfile/PKGFILE
+++ b/pkgfile/PKGFILE
@@ -13,6 +13,34 @@ source=("git+${url}.git")
 md5sums=('SKIP')
 depends=("bash>=0" smartmontools umc pigz geoip geoipupdate)
 
+# ---- cores (POSIX / sh-safe) -------------------------
+if [ -t 1 ]; then
+  RED="$(printf '\033[1;31m')"
+  GREEN="$(printf '\033[1;32m')"
+  YELLOW="$(printf '\033[1;33m')"
+  CYAN="$(printf '\033[1;36m')"
+  RESET="$(printf '\033[0m')"
+fi
+# ------------------------------------------------------
+
+log() {
+  printf "%s[*]%s %s - %s\n" "$CYAN" "$RESET" "$pkgname" "$*" >&2
+}
+
+warn() {
+  printf "%s[*]WARNING:%s %s - %s\n" "$YELLOW" "$RESET" "$pkgname" "$*" >&2
+  exit 1
+}
+
+die() {
+	printf "%s[*]FATAL:%s %s - %s\n" "$RED" "$RESET" "$pkgname" "$*" >&2
+	exit 1
+}
+
+require_cmd() {
+  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
+}
+
 package() {
 	local dirs=("usr" "etc" "opt")
 	#   echo "DESTDIR=$DESTDIR"
@@ -20,9 +48,11 @@ package() {
 	#   echo "srcdir=$srcdir"
 	#   echo "_pkgsrc=$_pkgsrc"
 
+  log "Starting installation"
 	cd ${srcdir}/${pkgname}
 	for dir in "${dirs[@]}"; do
 		if [ -d "${_pkgsrc}/${dir}" ]; then
+      log "Copyando files from ${_pkgsrc}/${dir} to ${DESTDIR}/"
 			cp -a "${_pkgsrc}/${dir}" "$DESTDIR/"
 		fi
 	done
